version: "3"
services:
    web:
       image: nginx:latest
       ports:
         - "80:80"
       links:
         - php
       volumes:
         - /data/nginx/html:/usr/share/nginx/html
         - /data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
         - /data/nginx/conf.d:/etc/nginx/conf.d
         - /data/nginx/logs:/var/log/nginx
       networks:
         - code-network
    redis:
       image: redis
       ports:
         - "6379:6379"
       networks:
         - code-network
    php:
       image: php-sqlsrv-redis:latest
       ports:
         - "9000:9000"
       volumes:
         - /data/nginx/html:/var/www/html
       container_name: php
       networks:
         - code-network
       links:
         - redis
         - db
    db:
       image: mcr.microsoft.com/mssql/server:2019-CTP3.0-ubuntu
       ports:
         - "1433:1433"
       container_name: db
       networks:
         - code-network
       environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=Sam!123456
networks:
    code-network:
       driver: bridge
